# Project identification
sonar.projectKey=dropty-api-server
sonar.projectName=dropty-api-server
sonar.projectVersion=1.0

# Source directories
# Keep test scope empty unless you have a dedicated tests folder/pattern.
sonar.sources=.
sonar.tests=
sonar.exclusions=**/*.test.js,**/*.spec.js,**/test/**,**/tests/**,node_modules/**,coverage/**,.scannerwork/**,.git/**

# Coverage report path
# sonar.flutter.coverage.reportPath=coverage/lcov.info

# SonarQube server
sonar.host.url=http://localhost:9000

# Auth token (generate from SonarQube UI → My Account → Security → Tokens)
sonar.token=sqp_ec7916b240bb031a0d910aa521ef68cf42a06ca0

# Source encoding
sonar.sourceEncoding=UTF-8

# Change the branch name if you are analyzing a different branch (e.g., 'develop', 'feature-xyz', etc.)
sonar.branch.name=prod